### ISSUE TITLE
[Feature Request] Remove nova-fields dependency

### ISSUE THREAD

**Issue by dillingham** [64robots/nova-row#4]
Would absolutely love this package if it didn't require the overriding of Nova's fields with 3rd party implementation. I really feel the style choices you made should just be baked in, there isn't much need for using the class methods then.

**Comment by disitec** [comment]
R64 Fields are not required at all. We only recommend this because we need a custom style for horizontal display. You can use any field as long the style fits with your needs. R64 fields don't behavior different so there is no dependency. Feel free to suggest some improvements that could help with this styling issue even with built-in nova fields.

**Comment by dillingham** [comment]
@disitec Oh ok, awesome! I installed and it didn't look as beautiful as your demo using native fields. I just assumed it was a requirement. I will happily work on some css if you're open to it. I think anyone using this package would assume that it would provide some internal styling, atleast I would

**Comment by disitec** [comment]
We are open to solutions of course. I'll be happy to merge your PRs if they help !

**Comment by dillingham** [comment]
@disitec so I played with this a bit more

1: Using `R64\NovaFields\Text` has the proper keys and values
2: Using `Laravel\Nova\Fields\Text` the resulting json has keys but no values. 

`"items" => "[{"name":""},{"name":""}]"`

**Comment by disitec** [comment]
You're right. Native fields don't emit input event and Row Field doesn't realize that value has changed. Im adding a watcher for those cases.
